### ISSUE TITLE
iojs support

### ISSUE THREAD

**Issue by mike820324** [karlwestin/node-gumbo-parser#13]
Hello,
I have used nan to rewrite the node-gumbo.cc a little bit, the following is the diff link:
https://github.com/mike820324/node-gumbo-parser/commit/ff132164fe41395928724b6357192cba65742a8b

It should install properly in iojs v1.3.0.
Should I send a pull request?

**Comment by karlwestin** [comment]
This is really cool, yes i really want this!

Just one q, it seems like should nan be added in package.json somewhere, can you do that?
Thanks a lot, this looks great!

**Comment by mike820324** [comment]
Okay, I'll check it out later.
I found out that I accidentally messed up the code indent, I'll commit a new one for that.

**Comment by mike820324** [comment]
PR sent. :+1:

**Comment by karlwestin** [comment]
Again, very cool work!
