### ISSUE TITLE
Node 4 Compatibility

### ISSUE THREAD

**Issue by staugaard** [karlwestin/node-gumbo-parser#17]
Hey,

This library will not compile on Node 4. Any plans to make that work?

**Comment by karlwestin** [comment]
hi sorry for the late answer, yeah that should definitely be fixed, what error message are you seeing? What platform are you using? Thanks!

**Comment by karlwestin** [comment]
i've been looking into this a little bit, and it seems im hopelessly behind on the Nan (node native extensions) API. I have an update-nan branch https://github.com/karlwestin/node-gumbo-parser/tree/fix/update-nan but i need to update my xcode apparently (ref this issue https://github.com/nodejs/node/issues/2933) to check if it works. Hopefully i can do that when i get home
